(in-package #:kons-9)

(defun pick (ray view)
  (flet ((select (shape) (setf (is-selected? shape) t))
         (unselect (shape) (setf (is-selected? shape) nil)))
    (multiple-value-bind (xs-hit xs-miss) (intersect ray (scene view))
      (unless (null xs-hit)
        (select (car xs-hit))
        (mapc #'unselect (cdr xs-hit)))
      (mapc #'unselect xs-miss))))
